config/routes.rb
Rails.application.routes.draw do



  namespace :admin do
    resources :jokes
    resources :encouragements
    resources :desi_says_modals
    resources :ideas do
      get 'pending', on: :collection
      get 'reported', on: :collection
    end
    resources :available_emails do
      get 'import', on: :collection
      post 'bulk_upload', on: :collection
    end

    get 'login' => 'base#login'
    post 'sign_in' => 'base#sign_in'
    get 'logout' => 'base#logout'
  end

  get '/auth/:provider/callback', to: 'admin/base#sign_in'


  root to: 'home#index'

  get '/additional_content' => 'home#additional_content'

  post 'ask/desi'

  post 'signup'              => 'user#create'
  post 'login'               => 'user#login'
  post 'logout'              => 'user#logout'
  post 'reset'               => 'user#reset'
  post 'position'            => 'user#save_position'
  get  'position'            => 'user#get_position'
  get   'verify'             => 'user#verify'
  post  'resend_pin'         => 'user#resend_pin'
  post  'verify_pin'         => 'user#verify_pin'
  patch '/user/update_phone' => 'user#update_phone'
  get   '/user/profile'      => 'user#profile'
  get '/ideas/get'           => 'user#get_idea'
  post '/ideas/give'         => 'user#give_idea'
  post '/ideas/report'       => 'user#report_idea'
  post '/ideas/like'         => 'user#like_idea'
  post '/remind_me'          => 'user#remind_me'

  get '/finance_details/:step' => 'home#index'
  patch '/finance_details'     => 'people#update_details'

  patch  '/people/children' => 'people#update_children'
  post   '/people'          => 'people#create'
  patch  '/people/:id'      => 'people#update'
  delete '/people/:id'      => 'people#destroy'

  post '/import/widget' => 'mx#widget'
  get '/import/connections' => 'mx#connections'
  post 'import/connections' => 'mx#on_create_connection'
  get '/import/connections/:id' => 'mx#get_connection'
  delete '/import/connections/:id' => 'mx#remove_connection'
  get '/import/balances' => 'mx#get_balances'
  get '/import/credit_charges' => 'mx#get_credit_charges'
  get '/import/loans' => 'mx#get_loans'
  get '/import/accounts_length' => 'mx#get_accounts_length'
  get '/import/dashboard_data' => 'mx#get_dashboard_data'

  post '/big_decision/solve' => 'big_decision#solve'
  post '/different_decisions/solve' => 'big_decision#solve_different'
  post '/defaults' => 'big_decision#defaults'

  get '/future_history/:step' => 'home#index'

  get '/future_assumptions/:step'  => 'home#index'
  get '/different_decisions/:step' => 'home#index'
  get '/budget_walkthrough/:step'  => 'home#index'
  get '/savings_loans/:step'       => 'home#index'

  patch '/budget_needs'      => 'people#update_budget_needs'
  patch '/budget_categories' => 'people#update_budget_categories'
  patch '/budget_tracking' => 'people#update_tracking_info'
  patch '/loans' => 'people#update_loans'
  patch '/investments' => 'people#update_investments'
  get '/unsubscribe/:unsubscribe_hash' => 'people#cancel_tracking', :as => 'unsubscribe'

  get ':page' => 'home#index'
  #get 'hello_world', to: 'hello_world#index'
end

app/models/desi_says_modal.rb
class DesiSaysModal < ApplicationRecord
  include ChangeableContent

  def as_json
    temp = super
    temp[:path] = self.slug
    temp
  end

end

app/controllers/admin/desi_says_modals_controller.rb
class Admin::DesiSaysModalsController < Admin::BaseController
  before_action :set_desi_says_modal, only: [:show, :edit, :update]

  def index
    @desi_says_modals = DesiSaysModal.all.order('id desc')
  end

  def show
  end

  def new
    @desi_says_modal = DesiSaysModal.new
  end

  def edit
  end

  def create
    @desi_says_modal = DesiSaysModal.new(desi_says_modal_params)

    respond_to do |format|
      if @desi_says_modal.save
        format.html { redirect_to admin_desi_says_modals_path, notice: 'Bubble was successfully created.' }
        format.json { render :show, status: :created, location: @desi_says_modal }
      else
        format.html { render :new }
        format.json { render json: @desi_says_modal.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @desi_says_modal.update(desi_says_modal_params)
        format.html { redirect_to admin_desi_says_modals_path, notice: 'Bubble was successfully updated.' }
        format.json { render :show, status: :ok, location: @desi_says_modal }
      else
        format.html { render :edit }
        format.json { render json: @desi_says_modal.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_desi_says_modal
      @desi_says_modal = DesiSaysModal.find(params[:id])
    end

    def desi_says_modal_params
      ps = params.require(:desi_says_modal).permit(:module, :slug, :content)
      ps[:content] =  ActionController::Base.helpers.sanitize(ps[:content]).gsub('"','\'')
      ps
    end
end

app/views/admin/desi_says_modals/_form.html.erb
<%= form_with(model: [:admin, desi_says_modal], local: true) do |form| %>
  <% if desi_says_modal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(desi_says_modal.errors.count, "error") %> prohibited this bubble from being saved:</h2>

      <ul>
      <% desi_says_modal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :module %>
    <%= form.text_field :module, id: :desi_says_modal_module %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug, id: :desi_says_modal_slug %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :desi_says_modal_content, rows: 5, cols: 50 %>
  </div>

  <div class="actions">
    <%= form.submit 'Save' %>
  </div>
<% end %>

app/views/admin/desi_says_modals/edit.html.erb
<h1>Editing Bubble</h1>

<%= render 'form', desi_says_modal: @desi_says_modal %>

<%= link_to 'Back', admin_desi_says_modals_path %>

app/views/admin/desi_says_modals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bubbles</h1>

<table class='table-with-entity'>
  <thead>
    <tr>
      <th>Module</th>
      <th>Path</th>
      <th>Content</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @desi_says_modals.each do |desi_says_modal| %>
      <tr>
        <td><%= desi_says_modal.module %></td>
        <td><%= desi_says_modal.slug %></td>
        <td><%= desi_says_modal.content %></td>
        <td><%= link_to 'Edit', edit_admin_desi_says_modal_path(desi_says_modal), role: 'edit-link' %></td>
      </tr>
    <% end %>
  </tbody>
</table>