config/routes.rb
Rails.application.routes.draw do



  namespace :admin do
    resources :jokes
    resources :encouragements
    resources :desi_says_modals
    resources :ideas do
      get 'pending', on: :collection
      get 'reported', on: :collection
    end
    resources :available_emails do
      get 'import', on: :collection
      post 'bulk_upload', on: :collection
    end

    get 'login' => 'base#login'
    post 'sign_in' => 'base#sign_in'
    get 'logout' => 'base#logout'
  end

  get '/auth/:provider/callback', to: 'admin/base#sign_in'


  root to: 'home#index'

  get '/additional_content' => 'home#additional_content'

  post 'ask/desi'

  post 'signup'              => 'user#create'
  post 'login'               => 'user#login'
  post 'logout'              => 'user#logout'
  post 'reset'               => 'user#reset'
  post 'position'            => 'user#save_position'
  get  'position'            => 'user#get_position'
  get   'verify'             => 'user#verify'
  post  'resend_pin'         => 'user#resend_pin'
  post  'verify_pin'         => 'user#verify_pin'
  patch '/user/update_phone' => 'user#update_phone'
  get   '/user/profile'      => 'user#profile'
  get '/ideas/get'           => 'user#get_idea'
  post '/ideas/give'         => 'user#give_idea'
  post '/ideas/report'       => 'user#report_idea'
  post '/ideas/like'         => 'user#like_idea'
  post '/remind_me'          => 'user#remind_me'

  get '/finance_details/:step' => 'home#index'
  patch '/finance_details'     => 'people#update_details'

  patch  '/people/children' => 'people#update_children'
  post   '/people'          => 'people#create'
  patch  '/people/:id'      => 'people#update'
  delete '/people/:id'      => 'people#destroy'

  post '/import/widget' => 'mx#widget'
  get '/import/connections' => 'mx#connections'
  post 'import/connections' => 'mx#on_create_connection'
  get '/import/connections/:id' => 'mx#get_connection'
  delete '/import/connections/:id' => 'mx#remove_connection'
  get '/import/balances' => 'mx#get_balances'
  get '/import/credit_charges' => 'mx#get_credit_charges'
  get '/import/loans' => 'mx#get_loans'
  get '/import/accounts_length' => 'mx#get_accounts_length'
  get '/import/dashboard_data' => 'mx#get_dashboard_data'

  post '/big_decision/solve' => 'big_decision#solve'
  post '/different_decisions/solve' => 'big_decision#solve_different'
  post '/defaults' => 'big_decision#defaults'

  get '/future_history/:step' => 'home#index'

  get '/future_assumptions/:step'  => 'home#index'
  get '/different_decisions/:step' => 'home#index'
  get '/budget_walkthrough/:step'  => 'home#index'
  get '/savings_loans/:step'       => 'home#index'

  patch '/budget_needs'      => 'people#update_budget_needs'
  patch '/budget_categories' => 'people#update_budget_categories'
  patch '/budget_tracking' => 'people#update_tracking_info'
  patch '/loans' => 'people#update_loans'
  patch '/investments' => 'people#update_investments'
  get '/unsubscribe/:unsubscribe_hash' => 'people#cancel_tracking', :as => 'unsubscribe'

  get ':page' => 'home#index'
  #get 'hello_world', to: 'hello_world#index'
end

app/models/joke.rb
class Joke < ApplicationRecord
  include ChangeableContent
end

app/controllers/admin/jokes_controller.rb
class Admin::JokesController < Admin::BaseController
  before_action :set_joke, only: [:show, :edit, :update, :destroy]
  layout 'staff'

  def index
    @jokes = Joke.all
  end

  def show
  end

  def new
    @joke = Joke.new
  end

  def edit
  end

  def create
    @joke = Joke.new(joke_params)

    respond_to do |format|
      if @joke.save
        format.html { redirect_to admin_jokes_path, notice: 'Joke was successfully created.' }
        format.json { render :show, status: :created, location: @joke }
      else
        format.html { render :new }
        format.json { render json: @joke.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @joke.update(joke_params)
        format.html { redirect_to admin_jokes_path, notice: 'Joke was successfully updated.' }
        format.json { render :show, status: :ok, location: @joke }
      else
        format.html { render :edit }
        format.json { render json: @joke.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @joke.destroy
    respond_to do |format|
      format.html { redirect_to admin_jokes_url, notice: 'Joke was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_joke
      @joke = Joke.find_by_id(params[:id])
      unless @joke
        redirect_to admin_jokes_path, notice: "Joke ##{params[:id]} is not existed."
      end
    end

    def joke_params
      ps = params.require(:joke).permit(:content)
      ps[:content] =  ActionController::Base.helpers.sanitize(ps[:content])
      ps
    end
end

app/views/admin/jokes/_form.html.erb
<%= form_with(model: [:admin, joke], local: true) do |form| %>
  <% if joke.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(joke.errors.count, "error") %> prohibited this joke from being saved:</h2>

      <ul>
      <% joke.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :joke_content, rows: 5, cols: 50 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/jokes/edit.html.erb
<h1>Editing Joke</h1>

<%= render 'form', joke: @joke %>

<%= link_to 'Back', admin_jokes_path %>

app/views/admin/jokes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jokes</h1>

<table class='table-with-entity'>
  <thead>
  </thead>

  <tbody>
    <% @jokes.each do |joke| %>
      <tr>
        <td><%= joke.content %></td>
        <td><%= link_to 'Edit', edit_admin_joke_path(joke), role: 'edit-link' %></td>
        <td><%= link_to 'Destroy', admin_joke_path(joke), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Joke', new_admin_joke_path %>

app/views/admin/jokes/new.html.erb
<h1>New Joke</h1>

<%= render 'form', joke: @joke %>

<%= link_to 'Back', admin_jokes_path %>