config/routes.rb
Rails.application.routes.draw do



  namespace :admin do
    resources :jokes
    resources :encouragements
    resources :desi_says_modals
    resources :ideas do
      get 'pending', on: :collection
      get 'reported', on: :collection
    end
    resources :available_emails do
      get 'import', on: :collection
      post 'bulk_upload', on: :collection
    end

    get 'login' => 'base#login'
    post 'sign_in' => 'base#sign_in'
    get 'logout' => 'base#logout'
  end

  get '/auth/:provider/callback', to: 'admin/base#sign_in'


  root to: 'home#index'

  get '/additional_content' => 'home#additional_content'

  post 'ask/desi'

  post 'signup'              => 'user#create'
  post 'login'               => 'user#login'
  post 'logout'              => 'user#logout'
  post 'reset'               => 'user#reset'
  post 'position'            => 'user#save_position'
  get  'position'            => 'user#get_position'
  get   'verify'             => 'user#verify'
  post  'resend_pin'         => 'user#resend_pin'
  post  'verify_pin'         => 'user#verify_pin'
  patch '/user/update_phone' => 'user#update_phone'
  get   '/user/profile'      => 'user#profile'
  get '/ideas/get'           => 'user#get_idea'
  post '/ideas/give'         => 'user#give_idea'
  post '/ideas/report'       => 'user#report_idea'
  post '/ideas/like'         => 'user#like_idea'
  post '/remind_me'          => 'user#remind_me'

  get '/finance_details/:step' => 'home#index'
  patch '/finance_details'     => 'people#update_details'

  patch  '/people/children' => 'people#update_children'
  post   '/people'          => 'people#create'
  patch  '/people/:id'      => 'people#update'
  delete '/people/:id'      => 'people#destroy'

  post '/import/widget' => 'mx#widget'
  get '/import/connections' => 'mx#connections'
  post 'import/connections' => 'mx#on_create_connection'
  get '/import/connections/:id' => 'mx#get_connection'
  delete '/import/connections/:id' => 'mx#remove_connection'
  get '/import/balances' => 'mx#get_balances'
  get '/import/credit_charges' => 'mx#get_credit_charges'
  get '/import/loans' => 'mx#get_loans'
  get '/import/accounts_length' => 'mx#get_accounts_length'
  get '/import/dashboard_data' => 'mx#get_dashboard_data'

  post '/big_decision/solve' => 'big_decision#solve'
  post '/different_decisions/solve' => 'big_decision#solve_different'
  post '/defaults' => 'big_decision#defaults'

  get '/future_history/:step' => 'home#index'

  get '/future_assumptions/:step'  => 'home#index'
  get '/different_decisions/:step' => 'home#index'
  get '/budget_walkthrough/:step'  => 'home#index'
  get '/savings_loans/:step'       => 'home#index'

  patch '/budget_needs'      => 'people#update_budget_needs'
  patch '/budget_categories' => 'people#update_budget_categories'
  patch '/budget_tracking' => 'people#update_tracking_info'
  patch '/loans' => 'people#update_loans'
  patch '/investments' => 'people#update_investments'
  get '/unsubscribe/:unsubscribe_hash' => 'people#cancel_tracking', :as => 'unsubscribe'

  get ':page' => 'home#index'
  #get 'hello_world', to: 'hello_world#index'
end

app/models/idea.rb
class Idea < ApplicationRecord
  before_save :sanitize_content
  scope :approved, -> { where(approved: true) }
  scope :pending, -> { where(approved: false) }
  scope :reported, -> { where(reported: true) }
  scope :with_likes, -> { includes(:likes) }
  has_many :likes, class_name: 'IdeaLike'

  TITLES = {
    basics:  'Basics',
    love:    'Love & Friendship',
    respect: 'Respect & Pride',
    expert:  'Being Good at Something',
    control: 'In Control of Your Life',
    helping: 'Helping Others',
    fun:     'Leisure & Fun',
    none:    'Other'
  }

  SAVES_MONEY = {
    0 => 'Costs nothing',
    1 => 'Save money',
    2 => 'Make money'
  }

  def need_s
    TITLES[need.to_sym]
  end

  def saves_money_s
    SAVES_MONEY[saves_money]
  end

  def as_short_json
    {
      id: id,
      saves_money: saves_money,
      content: content,
      user: our? ? user_name : 'Anonymous'
    }
  end

  def report!
    unless our?
      self.reported = true
      self.save
    end
  end

  def like!(user)
    if approved? && !likes.by(user).exists?
      like = likes.build(user_id: user.id)
      like.save!
    end
  end

  def our?
    user_id == 0
  end

private

  include ActionView::Helpers
  def sanitize_content
    unless our?
      self.content = sanitize(content, tags: ['br'])
    end
    self.content.gsub!("\n", "<br/>")
  end

end

app/controllers/admin/ideas_controller.rb
class Admin::IdeasController < Admin::BaseController
  include ApplicationHelper
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.approved.with_likes
  end

  def pending
    @ideas = Idea.pending.with_likes
    render 'index'
  end

  def reported
    @ideas = Idea.reported.with_likes
    render 'index'
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to [:admin,@idea], notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to [:admin, @idea], notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to admin_idea_back_path(@idea), notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      ps = params.require(:idea).permit(:need, :user_id, :approved, :reported, :user_name, :user_email, :saves_money, :content)
      ps[:content] =  ActionController::Base.helpers.sanitize(ps[:content]).gsub('"','\'')
      ps
    end
end

app/views/admin/ideas/_form.html.erb
<%= form_with(model: [:admin, idea], local: true) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :reported %>
    <%= form.check_box :reported, id: :idea_reported %>
  </div>

  <div class="field">
    <%= form.label :approved %>
    <%= form.check_box :approved, id: :idea_approved %>
  </div>

  <div class="field">
    <%= form.label :need %>
    <%= form.select :need, [['All', 'all']] + Idea::TITLES.to_a.collect(&:reverse), { include_blank: false }, id: :idea_need %>
    <%= form.select :saves_money, Idea::SAVES_MONEY.to_a.collect(&:reverse), { include_blank: false }, id: :idea_saves_money %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :idea_content, cols: 50, rows: 5 %>
  </div>

  <div class="field">
    <%= form.label :user_id, 'User #' %>
    <%= form.number_field :user_id, id: :idea_user_id %>
  </div>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name, id: :idea_user_name %>
  </div>

  <div class="field">
    <%= form.label :user_email %>
    <%= form.text_field :user_email, id: :idea_user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', [:admin, @idea] %> |
<%= link_to 'Back', admin_idea_back_path(@idea) %>

app/views/admin/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>

<table class='table-with-entity'>
  <thead>
    <tr>
      <th>Need</th>
      <th>Saves money</th>
      <th>Content</th>
      <th>User</th>
      <th>User name</th>
      <th>User email</th>
      <th>Likes count</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.need %></td>
        <td><%= idea.saves_money_s %></td>
        <td><%= idea.content %></td>
        <td><%= idea.user_id %></td>
        <td><%= idea.user_name %></td>
        <td><%= idea.user_email %></td>
        <td><%= idea.likes.count %></td>



        <td><%= link_to 'Show', [:admin, idea] %></td>
        <td><%= link_to 'Edit', edit_admin_idea_path(idea), role: 'edit-link' %></td>
        <td><%= link_to 'Destroy', [:admin, idea], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_admin_idea_path %>

app/views/admin/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', admin_ideas_path %>

app/views/admin/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Approved:</strong>
  <%= @idea.approved %>
  &nbsp;&nbsp;
  <strong>Reported:</strong>
  <%= @idea.reported %>
</p>

<p>
  <strong>Need:</strong>
  <%= @idea.need_s %>
  (<%= @idea.saves_money_s %>)
</p>

<p>
  <strong>Content:</strong>
  <%= sanitize(@idea.content).html_safe %>
</p>

<p>
  <strong>User:</strong>
  <%= @idea.user_id %>
  /
  <%= @idea.user_name %>
  /
  <%= @idea.user_email %>
</p>


<%= link_to 'Edit', edit_admin_idea_path(@idea) %> |
<%= link_to 'Back', admin_idea_back_path(@idea) %>