config/routes.rb
Rails.application.routes.draw do



  namespace :admin do
    resources :jokes
    resources :encouragements
    resources :desi_says_modals
    resources :ideas do
      get 'pending', on: :collection
      get 'reported', on: :collection
    end
    resources :available_emails do
      get 'import', on: :collection
      post 'bulk_upload', on: :collection
    end

    get 'login' => 'base#login'
    post 'sign_in' => 'base#sign_in'
    get 'logout' => 'base#logout'
  end

  get '/auth/:provider/callback', to: 'admin/base#sign_in'


  root to: 'home#index'

  get '/additional_content' => 'home#additional_content'

  post 'ask/desi'

  post 'signup'              => 'user#create'
  post 'login'               => 'user#login'
  post 'logout'              => 'user#logout'
  post 'reset'               => 'user#reset'
  post 'position'            => 'user#save_position'
  get  'position'            => 'user#get_position'
  get   'verify'             => 'user#verify'
  post  'resend_pin'         => 'user#resend_pin'
  post  'verify_pin'         => 'user#verify_pin'
  patch '/user/update_phone' => 'user#update_phone'
  get   '/user/profile'      => 'user#profile'
  get '/ideas/get'           => 'user#get_idea'
  post '/ideas/give'         => 'user#give_idea'
  post '/ideas/report'       => 'user#report_idea'
  post '/ideas/like'         => 'user#like_idea'
  post '/remind_me'          => 'user#remind_me'

  get '/finance_details/:step' => 'home#index'
  patch '/finance_details'     => 'people#update_details'

  patch  '/people/children' => 'people#update_children'
  post   '/people'          => 'people#create'
  patch  '/people/:id'      => 'people#update'
  delete '/people/:id'      => 'people#destroy'

  post '/import/widget' => 'mx#widget'
  get '/import/connections' => 'mx#connections'
  post 'import/connections' => 'mx#on_create_connection'
  get '/import/connections/:id' => 'mx#get_connection'
  delete '/import/connections/:id' => 'mx#remove_connection'
  get '/import/balances' => 'mx#get_balances'
  get '/import/credit_charges' => 'mx#get_credit_charges'
  get '/import/loans' => 'mx#get_loans'
  get '/import/accounts_length' => 'mx#get_accounts_length'
  get '/import/dashboard_data' => 'mx#get_dashboard_data'

  post '/big_decision/solve' => 'big_decision#solve'
  post '/different_decisions/solve' => 'big_decision#solve_different'
  post '/defaults' => 'big_decision#defaults'

  get '/future_history/:step' => 'home#index'

  get '/future_assumptions/:step'  => 'home#index'
  get '/different_decisions/:step' => 'home#index'
  get '/budget_walkthrough/:step'  => 'home#index'
  get '/savings_loans/:step'       => 'home#index'

  patch '/budget_needs'      => 'people#update_budget_needs'
  patch '/budget_categories' => 'people#update_budget_categories'
  patch '/budget_tracking' => 'people#update_tracking_info'
  patch '/loans' => 'people#update_loans'
  patch '/investments' => 'people#update_investments'
  get '/unsubscribe/:unsubscribe_hash' => 'people#cancel_tracking', :as => 'unsubscribe'

  get ':page' => 'home#index'
  #get 'hello_world', to: 'hello_world#index'
end

app/models/available_email.rb
class AvailableEmail < ApplicationRecord

  scope :by_email, ->(email) {
    name, domain = email.split('@')
    self.where("email_pattern = ? OR email_pattern = ?", email, '*@'+domain)
  }

  def self.valid?(email)
    by_email(email).exists?
  end

  def self.get_for(email)
    by_email(email).last
  end

end

app/controllers/admin/available_emails_controller.rb
class Admin::AvailableEmailsController < Admin::BaseController
  require 'csv'
  before_action :set_available_email, only: [:show, :edit, :update, :destroy]

  # GET /available_emails
  # GET /available_emails.json
  def index
    @available_emails = AvailableEmail.all
  end

  # GET /available_emails/1
  # GET /available_emails/1.json
  def show
  end

  # GET /available_emails/new
  def new
    @available_email = AvailableEmail.new
  end

  # GET /available_emails/1/edit
  def edit
  end

  # POST /available_emails
  # POST /available_emails.json
  def create
    @available_email = AvailableEmail.new(available_email_params)

    respond_to do |format|
      if @available_email.save
        format.html { redirect_to admin_available_emails_path, notice: 'Available email was successfully created.' }
        format.json { render :show, status: :created, location: @available_email }
      else
        format.html { render :new }
        format.json { render json: @available_email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /available_emails/1
  # PATCH/PUT /available_emails/1.json
  def update
    respond_to do |format|
      if @available_email.update(available_email_params)
        format.html { redirect_to admin_available_emails_path, notice: 'Available email was successfully updated.' }
        format.json { render :show, status: :ok, location: @available_email }
      else
        format.html { render :edit }
        format.json { render json: @available_email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /available_emails/1
  # DELETE /available_emails/1.json
  def destroy
    @available_email.destroy
    respond_to do |format|
      format.html { redirect_to admin_available_emails_url, notice: 'Available email was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
  end

  def bulk_upload
    file = params[:file]
    i = 0
    unless file
      redirect_to import_admin_available_emails_url, notice: "Please, choose import file."
      return
    end

    today_company = "Batch imported #{Date.today}"
    CSV.foreach(file.path) do |row|
      email = row[0]
      company = row[1] || today_company
      next if email.blank? || !email.include?('@')
      x = email.downcase
      next if AvailableEmail.where(email_pattern: x).exists?
      AvailableEmail.create(email_pattern: x, company: company)
      i += 1
    end
    redirect_to import_admin_available_emails_url, notice: "#{i} records were imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_available_email
      @available_email = AvailableEmail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def available_email_params
      params.require(:available_email).permit(:email_pattern, :company)
    end
end

app/helpers/available_emails_helper.rb
module AvailableEmailsHelper
end

app/views/admin/available_emails/_form.html.erb
<%= form_with(model: [:admin, available_email], local: true) do |form| %>
  <% if available_email.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(available_email.errors.count, "error") %> prohibited this available_email from being saved:</h2>

      <ul>
      <% available_email.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email_pattern %>
    <%= form.text_field :email_pattern, id: :available_email_email_pattern %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company, id: :available_email_company %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/available_emails/edit.html.erb
<h1>Editing White-listed Email</h1>

<%= render 'form', available_email: @available_email %>

<%= link_to 'Back', admin_available_emails_path %>

app/views/admin/available_emails/import.html.erb
<p id="notice"><%= notice %></p>

<h1>Importing Whilte-listed Emails</h1>


<%= form_tag bulk_upload_admin_available_emails_path, multipart: true do |form| %>
  <p>
    <%= file_field_tag :file, accept: 'text/csv' %>
    <%= submit_tag "Import CSV" %>
  </p>
<% end %>

<h3>Instruction</h3>
<p>Table should starts from the first row. Only CSV file is acceptable.</p>
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Company</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>email1@domain1.com</td>
      <td>company name 1</td>
    </tr>
    <tr>
      <td>email2@domain2.com</td>
      <td>company name 2</td>
    </tr>
  </tbody>
</table>

<%= link_to 'Back', admin_available_emails_path %>

app/views/admin/available_emails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>White-listed Emails</h1>

<table>
  <thead>
    <tr>
      <th>Email pattern</th>
      <th>Company</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @available_emails.each do |available_email| %>
      <tr>
        <td><%= available_email.email_pattern %></td>
        <td><%= available_email.company %></td>
        <td><%= link_to 'Edit', edit_admin_available_email_path(available_email) %></td>
        <td><%= link_to 'Destroy', [:admin, available_email], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New White-listed Email', new_admin_available_email_path %>

<br>
<%= link_to 'Import', import_admin_available_emails_path %>

app/views/admin/available_emails/new.html.erb
<h1>New Whilte-listed Email</h1>

<%= render 'form', available_email: @available_email %>

<%= link_to 'Back', admin_available_emails_path %>

app/views/admin/available_emails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email pattern:</strong>
  <%= @available_email.email_pattern %>
</p>

<p>
  <strong>Used count:</strong>
  <%= @available_email.used_count %>
</p>

<%= link_to 'Edit', edit_admin_available_email_path(@available_email) %> |
<%= link_to 'Back', admin_available_emails_path %>